apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: abakus
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: abakus
    newName: rg.fr-par.scw.cloud/djnd/abakus
    newTag: '9f7fb0f3eb4e6c473a3f7767b512104c716fefed'