apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: abakus
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: abakus
    newName: rg.fr-par.scw.cloud/djnd/abakus
    newTag: 'a7c71c4bb0df78161026ca15caf5564dadae916c'
